### ISSUE TITLE
Plain Text Only Option for Email Notifications

### ISSUE THREAD

**Issue by dasfreak** [RocketChat/feature-requests#187]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
I would like to see an option in the administration settings to switch from HTML emails to plain text only.

**Describe alternatives you've considered**
Currently, one would need to strip all HTML tags from the templates manually.
Switching back to HTML emails would be cumbersome again.

**Additional context**
none

**Comment by reetp** [comment]
Completely agree.

**Comment by reetp** [comment]
Users still can't get password resets or 2FA because html emails get blocked.

With email becoming a hard dependency this is becoming a bug, not just a NFR.

Please fix this.

<tests@domain.com>:
1.2.3.5 failed after I sent the message.
Remote host said: 552 Virus found: SecuriteInfo.com.Spam-1724.UNOFFICIAL
STARTTLS proto=TLSv1.2; cipher=ECDHE-RSA-AES256-GCM-SHA384; subject=/CN=domain.com; issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3;

Emails go via my own SMTP server and are DKIM signed etc etc and the server has good reputation.

But after testing, html mails are getting blocked completely by some recipient servers.

If I copy the html text to a mail with another client eg Thunderbird and via a different server it still gets blocked so it is the html body that is the problem.

I have tried to remove as many links as possible with no joy.

Converting it all to plain text including URLs passes without issues.

Still no idea why a chat system that is meant to replace email is making email a hard dependency, especially when it is so unreliable. Illogical.

**Comment by reetp** [comment]
So for alleged 'security' admins cannot change passwords for users in #15880 and the devs said they'd look at solutions to get round resulting issues.

@makibras 

> but want to help all for whom this was an actual change breaking their setup

So what are you going to do about it?

This is one blocker, and it is still being ignored.

If users do not a) receive emails and b) do not receive html emails they are barred from changing passwords.

So it is impossible to upgrade now. Which beats your supposed update to security because people will just stay with the 'unsecure' version because it is 'good enough for their use.

Or probably be easier to just move to a different solution now as no one here seems bothered about fixing these issues.
