### ISSUE TITLE
Pay enterprise, have cloud notifications and still have only the open source code

### ISSUE THREAD

**Issue by pierreozoux** [RocketChat/feature-requests#411]
**Is your feature request related to a problem? Please describe.**

Currently, if I sign up for enterprise, I receive a key, I put this key in my instance, and it activates the enterprise code (which is not open source).

**Describe the solution you'd like**

I'd like to be able to put the key (and have notifications), without the need to activate the non open source code.

**Describe alternatives you've considered**

I could pay AND compile myself the apps, but it would be a waste of energy :)

**Additional context**

We are an open source only hosting entity, we respect various charters, and are part of various organization, if we host non free software code, we'd be excluded from these organization.

**Comment by rodrigok** [comment]
@pierreozoux one thing is not attached to the other. Enterprise features and Push Notification limits are different things but may be included in the same plan we sell. So technically you can get more push limits through buying an enterprise plan and not apply the license to your server, you only need your server registered and the limits set to your server on our cloud since it's there where we count and limit the notifications. The only thing you need is to connect your server to our cloud, it can even be a version without the EE folder.

We have plans to automate a distribution without the EE folder in the future, it will require some work on the CI part and a solution to remove the EE dependencies we have in the CE code (just a few ones to initialize the EE code).

Does it solve your question?

**Comment by pierreozoux** [comment]
Thanks @rodrigok for taking the time.

it does solve the question for me!
