### ISSUE TITLE
Feature Request: Show password strength 

### ISSUE THREAD

**Issue by amitanshusahu** [RocketChat/feature-requests#868]
## Ui to show password Strength
when creating an account or changing password there should be something to show password strength 

![Screenshot 2023-09-18 at 12-34-40 Rocket Chat](https://github.com/RocketChat/Rocket.Chat/assets/83657737/e1cfa8aa-c5d6-4d0b-b14c-ce70aa64e9bf)

**Comment by amitanshusahu** [comment]
@hugocostadev  let me work on this

**Comment by KSSaiTeja** [comment]
i am interested to work on this..

**Comment by asv018** [comment]
I am working on it.

**Comment by dougfabris** [comment]
Hi there, thanks for the contribution! 🚀 💯 

Closing this issue request because we already have this feature, it's called `Password Policy`. 
You can activate it on your workspace by navigating to: Administration > Settings > Accounts > Password Policy

---

**Questions? Help needed? Feature Requests?** 

- Join our [Open Server](https://open.rocket.chat/) in the #support channel and feel free to raise a question
- Join our [Community Forum](https://forums.rocket.chat/) and search/create a post there
